@startuml er

!include ./config/default.inc

entity "users" as users {
    + **id**: int [PK]
    --
    * **name**: varchar(128)
    **password**: varchar(128)
    **public_key**: varchar(512)
    **secret_key**: varchar(512)
    **token**: varchar(128)
    **role**: varchar(32)
    **last_login_at**: datetime
    **created_at**: timestamp
    **updated_at**: timestamp
}

entity "events" as events {
    + **id** [PK]
    --
    **title**: varchar(128)
    **description**: varchar(512)
    **begin_at**: datetime
    **finished_at**: datetime
    **created_at**: timestamp
    **updated_at**: timestamp
}

entity "users_events" as users_events {
    + **id** [PK]
    --
    # **user_id**: int [FK]
    # **event_id**: int [FK]
    **created_at**: timestamp
    **updated_at**: timestamp
}

users -ri-o{ users_events: id:user_id
events -do-|{ users_events: id:event_id

@enduml